---

# Ensure all packages have been patched
- name: upgrade all packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true

- name: set use
  user:
    name: ubuntu
    password: "{{ 'testeroXc42ejGVk9' | password_hash('sha512') }}"
#     # shell: /bin/bash
#     # groups: adm,sys
    # append: yes
- name: set use2
  user:
    name: tester
    password: "{{ 'testeroXc42ejGVk9' | password_hash('sha512') }}"
    # shell: /bin/bash
    # groups: adm,sys
    append: yes
- name: set canfig
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication yes
    create: yes
- name: set canfig2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    state: absent
# - name: set canfig2.1
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^ChallengeResponseAuthentication no'
#     line: ChallengeResponseAuthentication yes
- name: set canfig2.2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^RSAAuthentication yes'
    line: RSAAuthentication no
- name: set canfig2.3
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication yes'
    line: PubkeyAuthentication no
- name: set canfig3
  shell: cat /etc/ssh/sshd_config
  register: canfig_out
- debug:
   var: canfig_out
- name: Validate the sudoers file before saving
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'tester    ALL=(ALL:ALL) ALL'
    validate: /usr/sbin/visudo -cf %s

# - name: restart serv
#   service:
#     name: ssh
#     state: restarted
