version: 2

jobs:

  validate:
    docker:
      - image: hashicorp/packer:latest
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer/base.json

  build-base-ami:
    docker:
      - image: hashicorp/packer:latest
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base ami
          command: ./packer/build.sh base ./packer/base.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-base.json
      - store_artifacts:
          path: manifest-base.json

# ------------------------------------------------------------------------------------

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base-ami:
          requires:
            - validate
