version: 2

jobs:

  packer-validate:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Validate Templates
          command: ls ./packer/*.json | xargs -I{} packer validate {}

  packer-build-ami:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Set creds
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir ~/.aws
              echo [default] >> ~/.aws/credentials
              echo aws_access_key_id=${awsa} >> ~/.aws/credentials
              echo aws_secret_access_key=${awss} >> ~/.aws/credentials
              echo [default] >> ~/.aws/config
              echo region=us-west-1 >> ~/.aws/config
              echo output=text >> ~/.aws/config
              export AWS_ACCESS_KEY_ID="${awsa}"
              export AWS_SECRET_ACCESS_KEY="${awss}"
              export AWS_DEFAULT_REGION="us-west-1"
            else
              export AWS_ACCESS_KEY_ID=${awsa}
              export AWS_SECRET_ACCESS_KEY=${awss}
              export AWS_DEFAULT_REGION="us-west-1"
            fi
      - run:
          name: Build base ami
          command: packer build ./packer/packer.json
          no_output_timeout: 30m

  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
      - run:
          name: Set creds
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir ~/.aws
              echo [default] >> ~/.aws/credentials
              echo aws_access_key_id=${awsa} >> ~/.aws/credentials
              echo aws_secret_access_key=${awss} >> ~/.aws/credentials
              echo [default] >> ~/.aws/config
              echo region=us-west-1 >> ~/.aws/config
              echo output=text >> ~/.aws/config
              export AWS_ACCESS_KEY_ID="${awsa}"
              export AWS_SECRET_ACCESS_KEY="${awss}"
              export AWS_DEFAULT_REGION="us-west-1"
            else
              export AWS_ACCESS_KEY_ID=${awsa}
              export AWS_SECRET_ACCESS_KEY=${awss}
              export AWS_DEFAULT_REGION="us-west-1"
            fi
      - run:
          name: terraform init
          command: cd ./terraform/ && terraform init
      - run:
          name: terraform plan
          command: cd ./terraform/ && terraform plan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Set creds
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir ~/.aws
              echo [default] >> ~/.aws/credentials
              echo aws_access_key_id=${awsa} >> ~/.aws/credentials
              echo aws_secret_access_key=${awss} >> ~/.aws/credentials
              echo [default] >> ~/.aws/config
              echo region=us-west-1 >> ~/.aws/config
              echo output=text >> ~/.aws/config
              export AWS_ACCESS_KEY_ID="${awsa}"
              export AWS_SECRET_ACCESS_KEY="${awss}"
              export AWS_DEFAULT_REGION="us-west-1"
            else
              export AWS_ACCESS_KEY_ID=${awsa}
              export AWS_SECRET_ACCESS_KEY=${awss}
              export AWS_DEFAULT_REGION="us-west-1"
            fi
      - run:
          name: terraform apply
          command: cd ./terraform/ && terraform apply
          environment:
            AWS_ACCESS_KEY_ID: ${awsa}
            AWS_SECRET_ACCESS_KEY: ${awss}
            AWS_DEFAULT_REGION: "us-west-1"

# ------------------------------------------------------------------------------------

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - packer-validate
      - packer-build-ami:
          requires:
            - packer-validate
      - terraform-plan:
          requires:
            - packer-build-ami
      - terraform-apply:
          requires:
            - terraform-plan
