---
- hosts: localhost
  connection: local
  gather_facts: true    # gather OS info that is made available for tasks/roles
  become: yes           # majority of CIS tasks require root

  vars:
    - go_ver: go1.12.6.linux-amd64.tar.gz

  roles:
  - common

  tasks:

    - name: Download go
      shell: 'wget https://dl.google.com/go/{{go_ver}}'

    - name: Extract go
      shell: 'tar -C /usr/local -xzf {{go_ver}}'

    - name: Set Paths
      shell: |
        export PATH=$PATH:/usr/local/go/bin
        export GOROOT=$HOME/go
        export PATH=$PATH:$GOROOT/bin
        export GOPATH=$HOME/projects/go/

    - name: Verify go
      command: /usr/local/go/bin/go version
      register: go_output

    - debug:
        var: go_output

    - name: Mkdir for btcd
      file:
        path: /usr/local/go/src/github.com/btcd/
        state: directory
        mode: '0755'

    - name: Checkout btcd repo
      git:
        repo: https://github.com/btcsuite/btcd.git
        dest: /usr/local/go/src/github.com/btcd/

    - name: Install btcd
      shell: cd /usr/local/go/src/github.com/btcd && GO111MODULE=on /usr/local/go/bin/go install -v . ./cmd/...
      environment:
        GOPATH: /usr/local/go/

###### TESTING ------------------------------------------------------------------------------------------------------------------------

# https://blog.hlongvu.com/post/akad7de26t-Understanding-btcd-Part-1-BTCD-overview

  # # Start btcd on simnet
  #   - name: Run btcd for testing
  #     shell: /usr/local/go/bin/btcd --simnet --rpcuser=testuser --rpcpass=testp4ssw0rd &
  #     register: run_btcd1
  #   - debug:
  #       var: run_btcd1

  # # Create test wallet
  # # etc....
  # # output tests
  # # kill btcd

  #   - name: btcctl - Unlock wallet
  #     shell: /usr/local/go/bin/btcctl --rpcuser=testuser --rpcpass=testp4ssw0rd --wallet --simnet walletpassphrase "test" 600
  #     register: run_btcctl_1
  #   - debug:
  #       var: run_btcctl_1

  #   - name: btcctl - Generate Accounts
  #     shell: /usr/local/go/bin/btcctl --rpcuser=testuser --rpcpass=testp4ssw0rd --simnet --wallet createnewaccount account1
  #     register: run_btcctl_2
  #   - debug:
  #       var: run_btcctl_2

  #   - name: btcctl - Generating Bitcoins
  #     shell: /usr/local/go/bin/btcctl --rpcuser=testuser --rpcpass=testp4ssw0rd --simnet --wallet getnewaddress
  #     register: run_btcctl_3
  #   - debug:
  #       var: run_btcctl_3

###### END TESTING --------------------------------------------------------------------------------------------------------------------

    - name: Run btcd
      shell: /usr/local/go/bin/btcd &
      register: run_btcd

    - debug:
        var: run_btcd

    - name: Start btcd at reboot in crontab
      cron:
        name: "Start btcd at reboot"
        special_time: reboot
        job: "/usr/local/go/bin/btcd &"
